package farmacia.view;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import farmacia.controller.Controller;
import farmacia.model.Model;

/**
 *
 * @author rogerio
 */
public class Principal extends javax.swing.JFrame {

    
    private Controller controller;
    
    public Principal(Controller controller) {
        
        initComponents();
        escalarImagemVenda("remedio.png");
        escalarImagemEstoque("remedio.png");
        centralizaTela();
        
        this.controller = controller;
        
    }
    
    public void centralizaTela(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public void escalarImagemVenda(String nomeImagem){
        
        ImageIcon imagemMudarTamanho = new javax.swing.ImageIcon(getClass().
                getResource("/farmacia/model/imagens/"+nomeImagem));
        
        Image img = imagemMudarTamanho.getImage();
        
        //Escala Imagen da venda
        Image imgEscalada = img.getScaledInstance(fotoLabelVenda.getWidth(),
                fotoLabelVenda.getHeight(), Image.SCALE_SMOOTH);        
        ImageIcon iconeEscalado = new ImageIcon(imgEscalada);        
        fotoLabelVenda.setIcon(iconeEscalado);

    }
    
    public void escalarImagemEstoque(String nomeImagem){
        
        ImageIcon imagemMudarTamanho = new javax.swing.ImageIcon(getClass().
                getResource("/farmacia/model/imagens/"+nomeImagem));
        
        Image img = imagemMudarTamanho.getImage();
        
        //escala Imagem do estoque
        Image imgEscalada = img.getScaledInstance(fotoLabelEstoque.getWidth(),
                fotoLabelEstoque.getHeight(), Image.SCALE_SMOOTH);        
        ImageIcon iconeEscalado= new ImageIcon(imgEscalada);        
        fotoLabelEstoque.setIcon(iconeEscalado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        titulo1jLabelVenda = new javax.swing.JLabel();
        listaLabelVenda = new javax.swing.JLabel();
        titulo2LabelVenda = new javax.swing.JLabel();
        fotoLabelVenda = new javax.swing.JLabel();
        pesquisarButtonVenda = new javax.swing.JButton();
        descricaoLabelVenda = new javax.swing.JLabel();
        adicionarButtonVenda = new javax.swing.JButton();
        titulo3LabelVenda = new javax.swing.JLabel();
        concluirButtonVenda = new javax.swing.JButton();
        titulo4LabelVenda = new javax.swing.JLabel();
        ListaDeRemediosComboBoxVenda = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        titulo1LabelEstoque = new javax.swing.JLabel();
        fotoLabelEstoque = new javax.swing.JLabel();
        pesquisarButtonEstoque = new javax.swing.JButton();
        descricaoLabelEstoque = new javax.swing.JLabel();
        titulo2LabelEstoque = new javax.swing.JLabel();
        titulo3LabelEstoque = new javax.swing.JLabel();
        quantidadeTextFieldEstoque = new javax.swing.JTextField();
        MudarButtonEstoque = new javax.swing.JButton();
        ListaDeRemediosComboBoxEstoque = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farmácia");
        setResizable(false);

        titulo1jLabelVenda.setText("Lista de itens");

        listaLabelVenda.setText("Nenhum");
        listaLabelVenda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listaLabelVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titulo2LabelVenda.setText("Pesquisar item");

        fotoLabelVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fotoLabelVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/model.imagens/remedio.png"))); // NOI18N
        fotoLabelVenda.setText("foto item");
        fotoLabelVenda.setToolTipText("");
        fotoLabelVenda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fotoLabelVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fotoLabelVenda.setPreferredSize(new java.awt.Dimension(110, 143));
        fotoLabelVenda.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        pesquisarButtonVenda.setText("Pesquisar");
        pesquisarButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarButtonVendaActionPerformed(evt);
            }
        });

        descricaoLabelVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        descricaoLabelVenda.setText("<html>Nome:?????<br><br>Preço:R$00,00<br><br>Quantidade:???<br><br><br>bula:<br>?????");
        descricaoLabelVenda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        descricaoLabelVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        adicionarButtonVenda.setText("Adicionar");

        titulo3LabelVenda.setText("<html>Adicionar item <br>na compra");

        concluirButtonVenda.setText("Concluir");
        concluirButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirButtonVendaActionPerformed(evt);
            }
        });

        titulo4LabelVenda.setText("Descrição do item");

        ListaDeRemediosComboBoxVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dorflex", "Xarelto", "Selozok", "Neosaldina", "Torsilax", "Aradois", "Glifage XR", "Addera D3", "Anthelios", "Buscopan composto" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo1jLabelVenda)
                            .addComponent(listaLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(concluirButtonVenda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(titulo2LabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addComponent(fotoLabelVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ListaDeRemediosComboBoxVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(pesquisarButtonVenda)
                        .addGap(81, 81, 81)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricaoLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo4LabelVenda)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adicionarButtonVenda)
                            .addComponent(titulo3LabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo1jLabelVenda)
                    .addComponent(titulo4LabelVenda)
                    .addComponent(titulo2LabelVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fotoLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo3LabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ListaDeRemediosComboBoxVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(listaLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concluirButtonVenda)
                    .addComponent(pesquisarButtonVenda)
                    .addComponent(adicionarButtonVenda))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Venda", jPanel1);

        titulo1LabelEstoque.setText("Pesquisar item");

        fotoLabelEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/model.imagens/remedio.png"))); // NOI18N
        fotoLabelEstoque.setText("foto item");
        fotoLabelEstoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pesquisarButtonEstoque.setText("Pesquisar");
        pesquisarButtonEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarButtonEstoqueActionPerformed(evt);
            }
        });

        descricaoLabelEstoque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        descricaoLabelEstoque.setText("<html>Nome:?????<br><br>Preço:R$00,00<br><br>Quantidade:???<br><br><br>bula:<br>?????");
        descricaoLabelEstoque.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        descricaoLabelEstoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titulo2LabelEstoque.setText("Descrição do item");

        titulo3LabelEstoque.setText("Mudar quantidade");

        quantidadeTextFieldEstoque.setText("000");

        MudarButtonEstoque.setText("Mudar");

        ListaDeRemediosComboBoxEstoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dorflex", "Xarelto", "Selozok", "Neosaldina", "Torsilax", "Aradois", "Glifage XR", "Addera D3", "Anthelios", "Buscopan composto" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fotoLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo1LabelEstoque))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ListaDeRemediosComboBoxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pesquisarButtonEstoque)
                    .addComponent(titulo2LabelEstoque)
                    .addComponent(descricaoLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantidadeTextFieldEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titulo3LabelEstoque)
                    .addComponent(MudarButtonEstoque))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo1LabelEstoque)
                    .addComponent(titulo2LabelEstoque)
                    .addComponent(titulo3LabelEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(quantidadeTextFieldEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MudarButtonEstoque)))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesquisarButtonEstoque)
                    .addComponent(ListaDeRemediosComboBoxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        jTabbedPane1.addTab("Estoque", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Tabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concluirButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirButtonVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concluirButtonVendaActionPerformed

    private void pesquisarButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarButtonVendaActionPerformed
                
        String itemSelecionado = ListaDeRemediosComboBoxVenda.
                            getSelectedItem().toString();
        
        String descricao = controller.retornaDescricao(itemSelecionado);
        
        descricaoLabelVenda.setText(descricao);
        escalarImagemVenda(controller.nomeImagem());
        
    }//GEN-LAST:event_pesquisarButtonVendaActionPerformed

    private void pesquisarButtonEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarButtonEstoqueActionPerformed
                
        String itemSelecionado = ListaDeRemediosComboBoxEstoque.
                            getSelectedItem().toString();
        
        String descricao = controller.retornaDescricao(itemSelecionado);
        
        descricaoLabelEstoque.setText(descricao);
        escalarImagemEstoque(controller.nomeImagem());
    }//GEN-LAST:event_pesquisarButtonEstoqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListaDeRemediosComboBoxEstoque;
    private javax.swing.JComboBox<String> ListaDeRemediosComboBoxVenda;
    private javax.swing.JButton MudarButtonEstoque;
    private javax.swing.JButton adicionarButtonVenda;
    private javax.swing.JButton concluirButtonVenda;
    private javax.swing.JLabel descricaoLabelEstoque;
    private javax.swing.JLabel descricaoLabelVenda;
    private javax.swing.JLabel fotoLabelEstoque;
    private javax.swing.JLabel fotoLabelVenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel listaLabelVenda;
    private javax.swing.JButton pesquisarButtonEstoque;
    private javax.swing.JButton pesquisarButtonVenda;
    private javax.swing.JTextField quantidadeTextFieldEstoque;
    private javax.swing.JLabel titulo1LabelEstoque;
    private javax.swing.JLabel titulo1jLabelVenda;
    private javax.swing.JLabel titulo2LabelEstoque;
    private javax.swing.JLabel titulo2LabelVenda;
    private javax.swing.JLabel titulo3LabelEstoque;
    private javax.swing.JLabel titulo3LabelVenda;
    private javax.swing.JLabel titulo4LabelVenda;
    // End of variables declaration//GEN-END:variables
}
