package farmacia.view;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import farmacia.controller.Controller;
import farmacia.model.Model;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author rogerio
 */
public class Principal extends javax.swing.JFrame {

    
    private Controller controller;
    private Float valorTotal;
    private String nomeItemVenda;
    private String nomeItemEstoque;
    private int quantidadeItemEstoque;
    
    public Principal(Controller controller) {
        
        initComponents();
        escalarImagemVenda("remedio.png");
        escalarImagemEstoque("remedio.png");
        centralizaTela();
        
        this.controller = controller;
        this.valorTotal = 0.00f;
        this.nomeItemVenda = "-";
        this.nomeItemEstoque = "-";  
        this.quantidadeItemEstoque = 0;
    }
    
    public void centralizaTela(){
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public void escalarImagemVenda(String nomeImagem){
        
        ImageIcon imagemMudarTamanho = new javax.swing.ImageIcon(getClass().
                getResource("/farmacia/model/imagens/"+nomeImagem));
        
        Image img = imagemMudarTamanho.getImage();
        
        //Escala Imagen da venda
        Image imgEscalada = img.getScaledInstance(fotoLabelVenda.getWidth(),
                fotoLabelVenda.getHeight(), Image.SCALE_SMOOTH);        
        ImageIcon iconeEscalado = new ImageIcon(imgEscalada);        
        fotoLabelVenda.setIcon(iconeEscalado);

    }
    
    public void escalarImagemEstoque(String nomeImagem){
        
        ImageIcon imagemMudarTamanho = new javax.swing.ImageIcon(getClass().
                getResource("/farmacia/model/imagens/"+nomeImagem));
        
        Image img = imagemMudarTamanho.getImage();
        
        //escala Imagem do estoque
        Image imgEscalada = img.getScaledInstance(fotoLabelEstoque.getWidth(),
                fotoLabelEstoque.getHeight(), Image.SCALE_SMOOTH);        
        ImageIcon iconeEscalado= new ImageIcon(imgEscalada);        
        fotoLabelEstoque.setIcon(iconeEscalado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        titulo1jLabelVenda = new javax.swing.JLabel();
        listaLabelVenda = new javax.swing.JLabel();
        titulo2LabelVenda = new javax.swing.JLabel();
        fotoLabelVenda = new javax.swing.JLabel();
        descricaoLabelVenda = new javax.swing.JLabel();
        adicionarButtonVenda = new javax.swing.JButton();
        titulo3LabelVenda = new javax.swing.JLabel();
        concluirButtonVenda = new javax.swing.JButton();
        titulo4LabelVenda = new javax.swing.JLabel();
        ListaDeRemediosComboBoxVenda = new javax.swing.JComboBox<>();
        valorTotalLabelVenda = new javax.swing.JLabel();
        limparButtonVendfa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        titulo1LabelEstoque = new javax.swing.JLabel();
        fotoLabelEstoque = new javax.swing.JLabel();
        descricaoLabelEstoque = new javax.swing.JLabel();
        titulo2LabelEstoque = new javax.swing.JLabel();
        titulo3LabelEstoque = new javax.swing.JLabel();
        quantidadeTextFieldEstoque = new javax.swing.JTextField();
        MudarButtonEstoque = new javax.swing.JButton();
        ListaDeRemediosComboBoxEstoque = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farmácia");
        setResizable(false);

        titulo1jLabelVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1jLabelVenda.setText("Lista de itens");

        listaLabelVenda.setText("<html>Nome / Preço<br><br>");
        listaLabelVenda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        listaLabelVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titulo2LabelVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2LabelVenda.setText("Pesquisar item");

        fotoLabelVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fotoLabelVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/model.imagens/remedio.png"))); // NOI18N
        fotoLabelVenda.setText("foto item");
        fotoLabelVenda.setToolTipText("");
        fotoLabelVenda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        fotoLabelVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fotoLabelVenda.setPreferredSize(new java.awt.Dimension(110, 143));
        fotoLabelVenda.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        descricaoLabelVenda.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        descricaoLabelVenda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        descricaoLabelVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        adicionarButtonVenda.setText("Adicionar");
        adicionarButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarButtonVendaActionPerformed(evt);
            }
        });

        titulo3LabelVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo3LabelVenda.setText("<html>Adicionar item <br>na compra");

        concluirButtonVenda.setText("Concluir");
        concluirButtonVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concluirButtonVendaActionPerformed(evt);
            }
        });

        titulo4LabelVenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo4LabelVenda.setText("Descrição do item");

        ListaDeRemediosComboBoxVenda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Dorflex", "Xarelto", "Selozok", "Neosaldina", "Torsilax", "Aradois", "Glifage XR", "Addera D3", "Anthelios", "Buscopan composto" }));
        ListaDeRemediosComboBoxVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaDeRemediosComboBoxVendaActionPerformed(evt);
            }
        });

        valorTotalLabelVenda.setText("Valor total R$ 0.00");
        valorTotalLabelVenda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        limparButtonVendfa.setText("Limpar");
        limparButtonVendfa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonVendfaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorTotalLabelVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(listaLabelVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(titulo1jLabelVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(concluirButtonVenda)
                            .addComponent(limparButtonVendfa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo2LabelVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListaDeRemediosComboBoxVenda, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fotoLabelVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(adicionarButtonVenda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo3LabelVenda)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(descricaoLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(titulo4LabelVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo1jLabelVenda)
                    .addComponent(titulo4LabelVenda)
                    .addComponent(titulo2LabelVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fotoLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titulo3LabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(listaLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorTotalLabelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(ListaDeRemediosComboBoxVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(limparButtonVendfa)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adicionarButtonVenda)
                    .addComponent(concluirButtonVenda))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Venda", jPanel1);

        titulo1LabelEstoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1LabelEstoque.setText("Pesquisar item");

        fotoLabelEstoque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmacia/model.imagens/remedio.png"))); // NOI18N
        fotoLabelEstoque.setText("foto item");
        fotoLabelEstoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        descricaoLabelEstoque.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        descricaoLabelEstoque.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        descricaoLabelEstoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        titulo2LabelEstoque.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2LabelEstoque.setText("Descrição do item");

        titulo3LabelEstoque.setText("Mudar quantidade");

        quantidadeTextFieldEstoque.setText("0");
        quantidadeTextFieldEstoque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantidadeTextFieldEstoqueKeyReleased(evt);
            }
        });

        MudarButtonEstoque.setText("Mudar");
        MudarButtonEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MudarButtonEstoqueActionPerformed(evt);
            }
        });

        ListaDeRemediosComboBoxEstoque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Dorflex", "Xarelto", "Selozok", "Neosaldina", "Torsilax", "Aradois", "Glifage XR", "Addera D3", "Anthelios", "Buscopan composto" }));
        ListaDeRemediosComboBoxEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaDeRemediosComboBoxEstoqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ListaDeRemediosComboBoxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fotoLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo1LabelEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descricaoLabelEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(titulo2LabelEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantidadeTextFieldEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titulo3LabelEstoque)
                            .addComponent(MudarButtonEstoque))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo1LabelEstoque)
                    .addComponent(titulo2LabelEstoque)
                    .addComponent(titulo3LabelEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fotoLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoLabelEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(quantidadeTextFieldEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MudarButtonEstoque)))
                .addGap(26, 26, 26)
                .addComponent(ListaDeRemediosComboBoxEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        jTabbedPane1.addTab("Estoque", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Tabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concluirButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concluirButtonVendaActionPerformed
        
        if(this.valorTotal == 0.00f){
            
            showMessageDialog(null, "Lista de compras vazia");
        }else{
            
            listaLabelVenda.setText("<html>Nome / Preço<br><br>");
        
            this.valorTotal = 0.00f;

            valorTotalLabelVenda.setText("Valor total R$ " + 
                    this.valorTotal.toString());

            showMessageDialog(null, "Venda realizada com sucesso");
            
        }
        
    }//GEN-LAST:event_concluirButtonVendaActionPerformed

    private void ListaDeRemediosComboBoxVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaDeRemediosComboBoxVendaActionPerformed
        
        if(ListaDeRemediosComboBoxVenda.getSelectedItem() != "-"){
            
            String itemSelecionado = ListaDeRemediosComboBoxVenda.
                            getSelectedItem().toString();
        
            ArrayList arrayRemedio = controller.retornaDescricao(itemSelecionado);
                    
                    
            String descricao = "<html>Nome: " + arrayRemedio.get(1).toString() +
                "<br><br>Preço: R$" + arrayRemedio.get(4).toString() +
                "<br><br>Quantidade: " + arrayRemedio.get(3).toString() +
                "<br><br><br>bula:<br>" + arrayRemedio.get(2).toString();  

            descricaoLabelVenda.setText(descricao);
            escalarImagemVenda(controller.nomeImagem());
            
        }else{
            descricaoLabelVenda.setText("");
            escalarImagemVenda("remedio.png");
        }
        
    }//GEN-LAST:event_ListaDeRemediosComboBoxVendaActionPerformed

    private void ListaDeRemediosComboBoxEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaDeRemediosComboBoxEstoqueActionPerformed
        
        if(ListaDeRemediosComboBoxEstoque.getSelectedItem() != "-"){
            
            String itemSelecionado = ListaDeRemediosComboBoxEstoque.
                            getSelectedItem().toString();
            
            ArrayList arrayRemedio = controller.retornaDescricao(itemSelecionado);
                    
                    
            String descricao = "<html>Nome: " + arrayRemedio.get(1).toString() +
                "<br><br>Preço: R$" + arrayRemedio.get(4).toString() +
                "<br><br>Quantidade: " + arrayRemedio.get(3).toString() +
                "<br><br><br>bula:<br>" + arrayRemedio.get(2).toString();          
            
            descricaoLabelEstoque.setText(descricao);
            escalarImagemEstoque(controller.nomeImagem());
            
        }else{
            
            descricaoLabelEstoque.setText("");
            escalarImagemEstoque("remedio.png");
        }
        
    }//GEN-LAST:event_ListaDeRemediosComboBoxEstoqueActionPerformed

    private void adicionarButtonVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarButtonVendaActionPerformed
        
        if(ListaDeRemediosComboBoxVenda.getSelectedItem() != "-"){
            
            String nomeItem = controller.getNome();
            Float precoItem = controller.getPreco();

            String listaString = listaLabelVenda.getText();

            listaString = listaString + nomeItem + " R$" + 
                    precoItem.toString() + "<br>";
            listaLabelVenda.setText(listaString);

            this.valorTotal = this.valorTotal + precoItem;

            valorTotalLabelVenda.setText("Valor total R$ " + 
                    this.valorTotal.toString());
        }       
        
    }//GEN-LAST:event_adicionarButtonVendaActionPerformed

    private void limparButtonVendfaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonVendfaActionPerformed
        
        listaLabelVenda.setText("<html>Nome / Preço<br><br>");
        
        this.valorTotal = 0.00f;

        valorTotalLabelVenda.setText("Valor total R$ " + 
                this.valorTotal.toString());
    }//GEN-LAST:event_limparButtonVendfaActionPerformed

    private void MudarButtonEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MudarButtonEstoqueActionPerformed
        
        if(!nomeItemEstoque.contains("-")){
            
            
            controller.mudaQuantidadeEstoque(this.quantidadeItemEstoque, 
                    this.nomeItemEstoque);
            
            String itemSelecionado = ListaDeRemediosComboBoxEstoque.
                            getSelectedItem().toString();
            
            ArrayList arrayRemedio = controller.retornaDescricao(itemSelecionado);
                    
                    
            String descricao = "<html>Nome: " + arrayRemedio.get(1).toString() +
                "<br><br>Preço: R$" + arrayRemedio.get(4).toString() +
                "<br><br>Quantidade: " + arrayRemedio.get(3).toString() +
                "<br><br><br>bula:<br>" + arrayRemedio.get(2).toString();          
            
            descricaoLabelEstoque.setText(descricao);
            escalarImagemEstoque(controller.nomeImagem());
            
        }
    }//GEN-LAST:event_MudarButtonEstoqueActionPerformed

    private void quantidadeTextFieldEstoqueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantidadeTextFieldEstoqueKeyReleased
        
        try {
            
            this.quantidadeItemEstoque = 
                    Integer.parseInt(quantidadeTextFieldEstoque.getText());
            
        } catch (NumberFormatException nfe) {
            
            quantidadeTextFieldEstoque.setText("0");
        }
    }//GEN-LAST:event_quantidadeTextFieldEstoqueKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ListaDeRemediosComboBoxEstoque;
    private javax.swing.JComboBox<String> ListaDeRemediosComboBoxVenda;
    private javax.swing.JButton MudarButtonEstoque;
    private javax.swing.JButton adicionarButtonVenda;
    private javax.swing.JButton concluirButtonVenda;
    private javax.swing.JLabel descricaoLabelEstoque;
    private javax.swing.JLabel descricaoLabelVenda;
    private javax.swing.JLabel fotoLabelEstoque;
    private javax.swing.JLabel fotoLabelVenda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton limparButtonVendfa;
    private javax.swing.JLabel listaLabelVenda;
    private javax.swing.JTextField quantidadeTextFieldEstoque;
    private javax.swing.JLabel titulo1LabelEstoque;
    private javax.swing.JLabel titulo1jLabelVenda;
    private javax.swing.JLabel titulo2LabelEstoque;
    private javax.swing.JLabel titulo2LabelVenda;
    private javax.swing.JLabel titulo3LabelEstoque;
    private javax.swing.JLabel titulo3LabelVenda;
    private javax.swing.JLabel titulo4LabelVenda;
    private javax.swing.JLabel valorTotalLabelVenda;
    // End of variables declaration//GEN-END:variables
}
